spring.application.name=Leads

spring.datasource.url=jdbc:postgresql://dpg-d7hotid8nd3s7387nk60-a.oregon-postgres.render.com:5432/leads_db_qbg1?sslmode=require
spring.datasource.username=leads_db_qbg1_user
spring.datasource.password=mb4HoutmHV10zV40JgL4IW9WOI06SU5N
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=marcialebogang7@gmail.com
spring.mail.password=zqkg qamt bfcs ncsm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true